packages:
  - 'packages/frontend/**/*'

catalog:
  'react': '^19.0.0'
  'react-dom': '^19.0.0'
  '@types/react-dom': '^19.0.4'
  '@types/react': '^19.0.10'
  '@vitejs/plugin-react': '^4.3.4'
  'typescript': '^5.7.2'
  'vite': '^6.2.0'
